name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Gradle Wrapper 8.9
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.9
          build-root-directory: .
          arguments: wrapper --gradle-version 8.9

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GodOfVPN-APK
          path: app/build/outputs/apk/debug/*.apk
